### ISSUE TITLE
Most Common Character - 01-31-2024

### ISSUE THREAD

**Issue by EwanStubblefield-Allen** [b1ueh4wk/challenges#26]
# Daily Challenge Issue Template

## Challenge Description

Given a string find the most common character that occurs and return the character. Use a JavaScript file and you can run it in the terminal using node [FILE_NAME].js.

## Acceptable Solution Standards

- Must take in a string (It can be a declared variable).
- Must return the character that occurs the most in said string.
- Attempt to use the fastest time complexity when completing the challenge

## Estimated Time for Completion

20-30 minutes

## Submission Guidelines
1. Assign yourself to this issue
2. Create a branch for yourself in this issue
3. Write your code locally
4. Push up your code to your branch on GitHub
5. Create a Pull Request to merge your code into main
6. Get reviewed by the "challenger"
7. Get merged or update your code as requested, and repeat 4, 5, 6.

**Comment by MichaelJHTaggart** [comment]
For challenges like this let's include "test cases" that expect a certain response. This makes it easier for others to know exactly what is acceptable, and if their code works. 

This is similar to how for the css challenges, we know exactly how it should look, and what is acceptable.

Here is an example of something we could do:

```javascript
function mostCommonCharacter(string){

 // Write your code here

}

// Test case #1:
mostCommonCharacter("aaaa"); // should return "a"
```

![Screenshot 2024-01-31 at 1 34 43 PM](https://github.com/b1ueh4wk/challenges/assets/63270278/f1e7bce2-0c2e-4848-aab8-b390c05f7da1)
