### ISSUE TITLE
CounterFunction Feb-13

### ISSUE THREAD

**Issue by FrancoLepe** [b1ueh4wk/challenges#54]
# Daily Challenge Issue Template

## Challenge Description

Make a button that increases the current count of 0 by 1 every time
and a Reset button that resets the count back to 0

<img width="325" alt="Screen Shot 2024-02-13 at 12 14 19 PM" src="https://github.com/b1ueh4wk/challenges/assets/118291178/10f94e88-e810-4d06-b0e4-2c8327ef589b">
<img width="335" alt="Screen Shot 2024-02-13 at 12 14 26 PM" src="https://github.com/b1ueh4wk/challenges/assets/118291178/dea59fbe-0795-42db-b309-956d21c2ea3a">

## Acceptable Solution Standards
30mins

## Submission Guidelines
1. Assign yourself to this issue
2. Create a branch for yourself in this issue
3. Write your code locally
4. Push up your code to your branch on GitHub
5. Create a Pull Request to merge your code into main
6. Get reviewed by the "challenger"
7. Get merged or update your code as requested, and repeat 4, 5, 6.

**Comment by MichaelJHTaggart** [comment]
Nice challenge!
