### ISSUE TITLE
Url Creator - 02-14-2024

### ISSUE THREAD

**Issue by EwanStubblefield-Allen** [b1ueh4wk/challenges#57]
# Daily Challenge Issue Template

## Challenge Description

Given a string convert it into an acceptable url (For this scope we will be focusing on spaces).

## Acceptable Solution Standards

- A function takes in a string
- Must return a string with the spaces altered to %20
- Attempt to use the fastest time complexity when completing the challenge

## Estimated Time for Completion

- Estimated time: 20-30 minutes

## Additional Notes or Resources (Optional)

```
function urlCreator(str) {
// Your code goes here
}
console.log(urlCreator('This is an url')) // Should return 'This%20is%20an%20url'
```
- To run you code in the terminal use the command node [FILE_NAME].js

## Submission Guidelines
1. Assign yourself to this issue
2. Create a branch for yourself in this issue
3. Write your code locally
4. Push up your code to your branch on GitHub
5. Create a Pull Request to merge your code into main
6. Get reviewed by the "challenger"
7. Get merged or update your code as requested, and repeat 4, 5, 6.

**Comment by MichaelJHTaggart** [comment]
Nice challenge! I love the simplicity!
